"""标签映射常量 —— 从 utils.constants 重导出（向后兼容）"""

from utils.constants import (  # noqa: F401  # 兼容重导出
    CONTRACT_STATUS_LABELS,
    CONFIRM_STATUS_LABELS,
    PAYMENT_STATUS_LABELS,
    CONFIDENCE_LABELS,
    PROCUREMENT_STATUS_LABELS,
    PROCUREMENT_METHOD_LABELS,
    PROCUREMENT_STAGE_ORDER,
    PROCUREMENT_STAGE_LABELS,
    PROCUREMENT_STAGE_STATUS_LABELS,
    CLARIFICATION_STATUS_LABELS,
    QUOTE_STATUS_LABELS,
    QUOTE_IMPORT_STATUS_LABELS,
)
